#!/usr/bin/env bash

# ====== Startup ===============================
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# ====== Variables =============================


gaps_top="5"
gaps_bottom="5"
gaps_left="5"
gaps_right="5"
gaps_inner="5"

# ====== Tiling settings =======================

yabai -m config layout                      bsp

yabai -m config top_padding                 "${gaps_top}"
yabai -m config bottom_padding              "${gaps_bottom}"
yabai -m config left_padding                "${gaps_left}"
yabai -m config right_padding               "${gaps_right}"
yabai -m config window_gap                  "${gaps_inner}"

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off
yabai -m config window_placement             second_child


yabai -m config mouse_modifier              shift
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.9
yabai -m config split_ratio                 0.5
yabai -m config auto_balance                off

# ====== Border settings =======================

# yabai -m config active_window_border_topmost on

yabai -m config external_bar all:23:0

yabai -m config window_border                on
yabai -m config active_window_border_color  0xFF679e6d
yabai -m config normal_window_border_color  0xFF3d4d3e
# yabai -m config insert_window_border_color   0xffFFFFAF
yabai -m config window_border_width         5



# ====== List of rules =========================
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="The Unarchiver" app="^The Unarchiver$" manage=off
yabai -m rule --add label="Transmission" app="^Transmission$" manage=off
yabai -m rule --add label="VirtualBox" app="^VirtualBox$" manage=off
yabai -m rule --add label="Info" app=".*Info$" manage=off

# regex that matches JetBrains apps
# apps='^(IntelliJ IDEA|WebStorm|CLion|PyCharm)$'

# float all JetBrains apps
# yabai -m rule --add app="${apps}" manage=off

# # add a signal that floats a window created by these apps when it's the only window
# yabai -m signal --add event=window_created app="${apps}" action='/Users/andy/.config/yabai/yabai_scripts/unfloat_only_window.sh'
# regex that matches JetBrains apps
# JetBrainsApp='^(IntelliJ IDEA|WebStorm|GoLand)$'
# yabai -m rule --add app="${JetBrainsApp}" manage=off
# yabai -m signal --add event=window_created app="${JetBrainsApp}" action="/Users/andy/.config/yabai/yabai_scripts/JetBrainsApp.sh"
